[package]
name = "alphadep"
version = "0.1.0"
edition = "2024"

[dependencies]
interface.workspace = true
runtime = { path = "./runtime", artifact = "bin" }
glob.workspace = true
zip.workspace = true
uuid = { version = "1.16.0", features = ["v4"] }
tokio-fs = "0.1.7"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tokio.workspace = true
toml.workspace = true
clap.workspace = true
shadow-rs.workspace = true
run_script = "0.11.0"
log.workspace = true
colog = "1.3.0"
futures = { version = "0.3.31", features = ["executor"] }
ctrlc = { version = "3.4.6", features = ["termination"]}
signal-hook = "0.3.17"
libssh2-sys = { git = "https://github.com/kappa8719/ssh2-rs", rev = "328064412d80bacef4c01cc07da8468799aaf266" }
ssh2 = { git = "https://github.com/kappa8719/ssh2-rs", rev = "328064412d80bacef4c01cc07da8468799aaf266" }

[workspace]
members = ["interface","runtime"]

[workspace.dependencies]
interface = { path = "./interface" }
zip = "2.6.1"
glob = "0.3.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
anyhow = "1.0.97"
tokio = { version = "1.44.1", features = ["fs", "io-std", "rt", "rt-multi-thread", "io-util", "net", "signal", "time"] }
toml = "0.8.20"
log = "0.4.27"
clap = { version = "4.5.35", features = ["derive"] }
shadow-rs = { version = "1.1.1", default-features = false }