[package]
name = "runtime-wrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
alphadep.workspace = true