[machine]
type = "remote/ssh"
host = "smtp.posts.kr"
user = "ubuntu"
identity = { type = "key", path = "/home/arcranion/.ssh/general_a.pem" }

[deployment]
id = "entropi.mailer"

[deployment.build]
machine = "master"

[deployment.runtime]
context = "session"
execute = ""

[deployment.files]
excludes = [".*"]
includes = [".env"]

[deployment.environment-variables]
build="1"